// <auto-generated />
namespace PCbuild_ASP.MVC_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MergeIdentityData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeIdentityData));
        
        string IMigrationMetadata.Id
        {
            get { return "201904201815167_MergeIdentityData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
