// <auto-generated />
namespace PCbuild_ASP.MVC_.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddGamePK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGamePK));
        
        string IMigrationMetadata.Id
        {
            get { return "201905081701120_AddGamePK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
